format = """
[](#844FBA)\
$username\
[](fg:#844FBA bg:#2E71E5)\
$directory\
[](fg:#2E71E5 bg:#DC477D)\
$git_branch\
$git_status\
[](fg:#DC477D bg:#8696D8)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#8696D8 bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#33658A)\
$time\
[ ](fg:#33658A)\
"""

# More time for commands to run in milliseconds
# https://starship.rs/config/#prompt
command_timeout = 750

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#844FBA"
style_root = "bg:#844FBA"
#format = '[$user ]($style)'
format = '[]($style)'

[directory]
style = "bg:#2E71E5"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#8696D8"
format = '[[ $symbol ($version) ](bg:#8696D8)]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[[ $symbol $context ](bg:#06969A)]($style) $path'

[elixir]
symbol = " "
style = "bg:#8696D8"
format = '[[ $symbol ($version) ](bg:#8696D8)]($style)'

[elm]
symbol = " "
style = "bg:#8696D8"
format = '[[ $symbol ($version) ](bg:#8696D8)]($style)'

[git_branch]
symbol = ""
style = "bg:#DC477D"
format = '[[ $symbol $branch ](bg:#DC477D)]($style)'

[git_status]
style = "bg:#DC477D"
format = '[[($all_status$ahead_behind )](bg:#DC477D)]($style)'

[golang]
symbol = " "
style = "bg:#8696D8"
format = '[[ $symbol ($version) ](bg:#8696D8)]($style)'

[haskell]
symbol = " "
style = "bg:#8696D8"
format = '[[ $symbol ($version) ](bg:#8696D8)]($style)'

[java]
symbol = " "
style = "bg:#8696D8"
format = '[[ $symbol ($version) ](bg:#8696D8)]($style)'

[julia]
symbol = " "
style = "bg:#8696D8"
format = '[[ $symbol ($version) ](bg:#8696D8)]($style)'

[nodejs]
symbol = ""
style = "bg:#8696D8"
format = '[[ $symbol ($version) ](bg:#8696D8)]($style)'

[nim]
symbol = " "
style = "bg:#8696D8"
format = '[[ $symbol ($version) ](bg:#8696D8)]($style)'

[rust]
symbol = ""
style = "bg:#8696D8"
format = '[[ $symbol ($version) ](bg:#8696D8)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[[ $time ](bg:#33658A)]($style)'

